theme: jekyll-theme-cayman

# Site Data
title: Shaun Yap
description: Shaun Yap's Github/Portfolio Page

# Google Analytics/Tracking
google_analytics: G-EHPGC3N6ET

page_excerpts: true

include: [_pages]

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root.