var restaurant = [
    //Unsorted
    'Provisions',
    'Big Wanton Mee',
    'Chicha Bonita',
    'Taco Bell',
    'Rocku Yakiniku',
    'Kuro',
    'Jakes Steak House',
    'Sala',

    // Paradigm + Vicinity
    'Kenny\'s Food Cart',
    'myBurgerLab',
    'Kar Heong Chicken Rice/Any Chicken Rice',
    'Undisclosed Location',
    'doudou',
    'Old Town White Coffee',
    'KD Hong Kong',
    'Pizza Hut',
    'Sushi Mentai',
    'Asian Rice Pot',
    'Acha\'s Curry House',
    'Nasi Lemak Bumbung',
    'Fatty Crab',
    'Sukiya',
    'Sushi Zanmai',
    'Chilli\'s',
    'Fei Fan Hotpot',
    'McDonalds',
    'KFC',
    'Ipoh Ais Kopi',
    'An Viet',
    'Penang Road Famous TeoChew Chendol',
    'Serai',
    'Canning Heritage Express',
    'Ginger Forever Thai',
    'Pork Meals',
    'Sepiring',
    'Sushi King',
    'Chicken Rice Shop',
    'Sukiya (Rice Bowl',
    'Aroi Thai',
    'FRK Noodle House',
    'GO Noodle',
    'Myeongdong Toppokki',
    'Canton Kitchen',
    'A&W',
    'Paradise Dynasty',
    'Sushi Zanmai',
    'Old Town',
    'I Love Yoo',
    'Nandos',
    'Burger King',
    'Fish n\' Co',
    'Seoul Garden',
    'd\'Italiene',
    'Kenny Rogers Roasters',
    'Ayamas',
    'Ah Cheng Laksa',
    'Kin Niku',
    'Food Arcade',
    'Salad Atelier',
    'Cravings',
    'Harum Manis',
    'Stuffd',
    'The Eatery',
    'Sushi Jiro',
    'Torii Tepanyaki',
    //If you're adding, make sure you're adding to the group below as well.

    // Jaya One + Vicinity
    'myBurgerLab',
    'Old Town White Coffee',
    'Ah Ma Kitchen',
    'Apple Samgyupsal',
    'Godubab Cafe',
    'Ippudo',
    'Kim Lian Kee',
    'Street Thai',
    'Subway',
    'Tedboy',
    'Tommy Thong Chai',
    'Uncle Chong Local Delights',
    'Sae Ma Eul',
    'Hannah Zen',
    'Lam Mee Ya',
    'Rumahku',
    'Shin Haru Tei',
    'Yakitori Syokudo Yae',
    'Ramenbar Shishido',
    'Picadilly',
    'Anjappar',
    'Bari Uma Ramen',
    'Enorme Italian Restaurant',
    'Grub by Ah Hong',
    'Zao',
    'Strangers at 47',
    'Jing Ze',
    'Aroi Mak Mak',
    'Kanna Curry House',
    'Tipsy Ball',
    'Omulab',
    'Big Leaf',
    // If you're adding, make sure you're adding to the group below as well.

    //One Utama
    'Aeon (Especially after 8!)',
    'Absolute Thai',
    'AK Noodle House',
    'Ante',
    'Bar BQ Plaza',
    'Big Fish Small Fish',
    'Black Canyon',
    'Boat Noodle',
    'Bong Chu Braised Chicken',
    'Burger King',
    'Canton - i',
    'Carls Jr',
    'Chillis',
    'Churitos',
    'Dave\'s Bistro',
    'Din Tai Fung',
    'Dookki',
    'Dragon - i',
    'Esquire Kitchen',
    'Fei Fan Hotpot',
    'Fish and Co',
    'FWF Hotpot',
    'Gantetsu',
    'Go Noodle',
    'Haidilao',
    'Hansang Korean',
    'Hokkaido Sushi',
    'Hong Kong Kim Gary',
    'Hotpot Kitchen',
    'House of Pok',
    'Ippudo',
    'K Fry',
    'Kenny Rogers Roasters',
    'Kluang Station',
    'Ko Hyang',
    'Kyochon',
    'L.Table',
    'Little Cravings',
    'Loong Cafe',
    'Loretta DOP',
    'Madam Kwan',
    'Mak\'s Chee',
    'Marco',
    'McDonalds',
    'Menya Musashi',
    'Morganfields',
    'Mr Fish Fish',
    'Nam Heong Ipoh',
    'Nandos',
    'Noodle Shack',
    'O\'Briens',
    'Old Siam',
    'Pho Viet',
    'Pizza Hut',
    'Porridge Time',
    'Putien',
    'Pao Xiang Bak Kut Teh',
    'Peranakan Place',
    'Robataya',
    'Rocku Yakiniku',
    'Sakae Sushi',
    'Sam Tai Yamch\'a',
    'Sekinchan Catch',
    'Seoul Garden',
    'Soup Restaurant',
    'Stuffd',
    'Subway',
    'Sushi King',
    'Sushi Ya',
    'Sushi Zanmai',
    'Teh Tarik Place',
    'Teow Chew Lor',
    'Teppanyaki',
    'Texas Chicken',
    'Thai Hou Sek',
    'The Chicken Rice Shop',
    'The Fish Bowl',
    'Manhattan Fish Market',
    'Tonkatsu by Ma Mai Son',
    'Union Cafe',
    'Wondermama',
    'Wong Kok Char Chan Teng',
    'Xiang by Nicsmaan',
    'Yakiniku Kuro',
    'Yishensu',
    'Yuen Room',
    'Yun Bridge Noodle',
    'Z Botanica',
    'Zhao Ji Chuan Cheng',
    'The Food District',
    'Melaka Corner',
    'Shilin',
    //If you're adding, make sure you're adding to the group below as well.

    // Starling
    'Ah Cheng Laksa',
    'Dave\'s Deli',
    'Din Dou Duck and Hou Yum Duck',
    'Jia Bao Bak Kut Teh',
    'Kakatoo',
    'Kam Kee Cafe',
    'Lim Fried Chicken',
    'Mala Jjiang Mala Ttang',
    'Mitsuyado Xeimen',
    'Mr Tuk Tuk',
    'Nandos',
    'Rakuzen',
    'Red Kettle',
    'Sala (Not yet opened in Starling)',
    'Salad Atelier',
    'Seppia and Polpol',
    'Sopoong',
    'Stuffd',
    'Sukishi',
    'Sushi Zanmai',
    'Taiwan Spicy Noodle House',
    'Teow Choo Lor',
    'Two Sons Bistro',
    'Uncle Soon Fried Rice',
    'Warung Sizzling',
    //If you're adding, make sure you're adding to the group below as well.

    // Atria
    'Boon Signature Roast Pork',
    'Jin Xuan Hong Kong Dim Sum',
    'Big Big Wanton Mee Rice',
    'Good Taste',
    'Boiling Mad Soup',
    'Itek Itik',
    'New Ipoh Nga Choy Chicken Rice',
    'Teow Chew Seafood Noodle House',
    'The Bons Cafe',
    'Go Thai',
    'Goon Wa XO Fish Head Noodle',
    'Spital Fields',
    'Mr Fish Seafood Noodle',
    'Oriental Musuem',
    'Little Penang Cafe',
    'Foo Ah Chin',
    'Gastro Village',
    'Moim Modern Korean Cuisine',
    'Subway',
    'Dynasty Dragon',
    'Esquire Kitchen',
    'Korean BBQ House',
    'Li',
    'Provisions',
    'Michele\'s Kitchen',
    'Restaurant Kampung Seafood Parit Jawa',
    'Vary Pasta',
    'Five Fingers Vegetarian Cafe',
    'Fugu Japanese Fusion',
    'The Chinatown',
    'The Magic Wok',
    'Kopitime Cafe',
    'Tan Sen Izakaya',
    'Chung Kee Claypot',
    'Pallets and Pans'
    //If you're adding, make sure you're adding to the group below as well.

    // Next Area
    //If you're adding, make sure you're adding to the group below as well.
]

var restaurantParadigm = [
    // Paradigm + Vicinity
    'Kenny\'s Food Cart',
    'myBurgerLab',
    'Kar Heong Chicken Rice/Any Chicken Rice',
    'Undisclosed Location',
    'doudou',
    'Old Town White Coffee',
    'KD Hong Kong',
    'Pizza Hut',
    'Sushi Mentai',
    'Asian Rice Pot',
    'Acha\'s Curry House',
    'Nasi Lemak Bumbung',
    'Fatty Crab',
    'Sukiya',
    'Sushi Zanmai',
    'Chilli\'s',
    'Fei Fan Hotpot',
    'McDonalds',
    'KFC',
    'Ipoh Ais Kopi',
    'An Viet',
    'Penang Road Famous TeoChew Chendol',
    'Serai',
    'Canning Heritage Express',
    'Ginger Forever Thai',
    'Pork Meals',
    'Sepiring',
    'Sushi King',
    'Chicken Rice Shop',
    'Sukiya (Rice Bowl',
    'Aroi Thai',
    'FRK Noodle House',
    'GO Noodle',
    'Myeongdong Toppokki',
    'Canton Kitchen',
    'A&W',
    'Paradise Dynasty',
    'Sushi Zanmai',
    'Old Town',
    'I Love Yoo',
    'Nandos',
    'Burger King',
    'Fish n\' Co',
    'Seoul Garden',
    'd\'Italiene',
    'Kenny Rogers Roasters',
    'Ayamas',
    'Ah Cheng Laksa',
    'Kin Niku',
    'Food Arcade',
    'Salad Atelier',
    'Cravings',
    'Harum Manis',
    'Stuffd',
    'The Eatery',
    'Sushi Jiro',
    'Torii Tepanyaki'
]

var restaurantJayaOne = [
    // Jaya One + Vicinity
    'myBurgerLab',
    'Old Town White Coffee',
    'Ah Ma Kitchen',
    'Apple Samgyupsal',
    'Godubab Cafe',
    'Ippudo',
    'Kim Lian Kee',
    'Street Thai',
    'Subway',
    'Tedboy',
    'Tommy Thong Chai',
    'Uncle Chong Local Delights',
    'Sae Ma Eul',
    'Hannah Zen',
    'Lam Mee Ya',
    'Rumahku',
    'Shin Haru Tei',
    'Yakitori Syokudo Yae',
    'Ramenbar Shishido',
    'Picadilly',
    'Anjappar',
    'Bari Uma Ramen',
    'Enorme Italian Restaurant',
    'Grub by Ah Hong',
    'Zao',
    'Strangers at 47',
    'Jing Ze',
    'Aroi Mak Mak',
    'Kanna Curry House',
    'Tipsy Ball',
    'Omulab',
    'Big Leaf'
]

var restaurantOneUtama = [
    // One Utama
    'Aeon (Especially after 8!)',
    'Absolute Thai',
    'AK Noodle House',
    'Ante',
    'Bar BQ Plaza',
    'Big Fish Small Fish',
    'Black Canyon',
    'Boat Noodle',
    'Bong Chu Braised Chicken',
    'Burger King',
    'Canton - i',
    'Carls Jr',
    'Chillis',
    'Churitos',
    'Dave\'s Bistro',
    'Din Tai Fung',
    'Dookki',
    'Dragon - i',
    'Esquire Kitchen',
    'Fei Fan Hotpot',
    'Fish and Co',
    'FWF Hotpot',
    'Gantetsu',
    'Go Noodle',
    'Haidilao',
    'Hansang Korean',
    'Hokkaido Sushi',
    'Hong Kong Kim Gary',
    'Hotpot Kitchen',
    'House of Pok',
    'Ippudo',
    'K Fry',
    'Kenny Rogers Roasters',
    'Kluang Station',
    'Ko Hyang',
    'Kyochon',
    'L.Table',
    'Little Cravings',
    'Loong Cafe',
    'Loretta DOP',
    'Madam Kwan',
    'Mak\'s Chee',
    'Marco',
    'McDonalds',
    'Menya Musashi',
    'Morganfields',
    'Mr Fish Fish',
    'Nam Heong Ipoh',
    'Nandos',
    'Noodle Shack',
    'O\'Briens',
    'Old Siam',
    'Pho Viet',
    'Pizza Hut',
    'Porridge Time',
    'Putien',
    'Pao Xiang Bak Kut Teh',
    'Peranakan Place',
    'Robataya',
    'Rocku Yakiniku',
    'Sakae Sushi',
    'Sam Tai Yamch\'a',
    'Sekinchan Catch',
    'Seoul Garden',
    'Soup Restaurant',
    'Stuffd',
    'Subway',
    'Sushi King',
    'Sushi Ya',
    'Sushi Zanmai',
    'Teh Tarik Place',
    'Teow Chew Lor',
    'Teppanyaki',
    'Texas Chicken',
    'Thai Hou Sek',
    'The Chicken Rice Shop',
    'The Fish Bowl',
    'Manhattan Fish Market',
    'Tonkatsu by Ma Mai Son',
    'Union Cafe',
    'Wondermama',
    'Wong Kok Char Chan Teng',
    'Xiang by Nicsmaan',
    'Yakiniku Kuro',
    'Yishensu',
    'Yuen Room',
    'Yun Bridge Noodle',
    'Z Botanica',
    'Zhao Ji Chuan Cheng',
    'The Food District',
    'Melaka Corner',
    'Shilin',
]

var restaurantStarling = [
    'Ah Cheng Laksa',
    'Dave\'s Deli',
    'Din Dou Duck and Hou Yum Duck',
    'Jia Bao Bak Kut Teh',
    'Kakatoo',
    'Kam Kee Cafe',
    'Lim Fried Chicken',
    'Mala Jjiang Mala Ttang',
    'Mitsuyado Xeimen',
    'Mr Tuk Tuk',
    'Nandos',
    'Rakuzen',
    'Red Kettle',
    'Sala (Not yet opened in Starling)',
    'Salad Atelier',
    'Seppia and Polpol',
    'Sopoong',
    'Stuffd',
    'Sukishi',
    'Sushi Zanmai',
    'Taiwan Spicy Noodle House',
    'Teow Choo Lor',
    'Two Sons Bistro',
    'Uncle Soon Fried Rice',
    'Warung Sizzling'
]

var restaurantAtria = [
    'Boon Signature Roast Pork',
    'Jin Xuan Hong Kong Dim Sum',
    'Big Big Wanton Mee Rice',
    'Good Taste',
    'Boiling Mad Soup',
    'Itek Itik',
    'New Ipoh Ngar Choy Chicken Rice',
    'Teow Chew Seafood Noodle House',
    'The Bons Cafe',
    'Go Thai',
    'Goon Wa XO Fish Head Noodle',
    'Spital Fields',
    'Mr Fish Seafood Noodle',
    'Oriental Musuem',
    'Little Penang Cafe',
    'Foo Ah Chin',
    'Gastro Village',
    'Moim Modern Korean Cuisine',
    'Subway',
    'Dynasty Dragon',
    'Esquire Kitchen',
    'Korean BBQ House',
    'Li',
    'Provisions',
    'Michele\'s Kitchen',
    'Restaurant Kampung Seafood Parit Jawa',
    'Vary Pasta',
    'Five Fingers Vegetarian Cafe',
    'Fugu Japanese Fusion',
    'The Chinatown',
    'The Magic Wok',
    'Kopitime Cafe',
    'Tan Sen Izakaya',
    'Chung Kee Claypot',
    'Pallets and Pans'
]

function loadedFunction() {
    document.getElementById('restaurantNumber').innerHTML = 'We\'ve got ' + restaurant.length.toString() + ' added to the list and counting!';
}

function pickClick() {
    var randomRestaurant = Math.floor(Math.random() * (restaurant.length));
    document.getElementById('restaurantHTML').innerHTML = restaurant[randomRestaurant];
    // document.getElementById('cuisineHTML').innerHTML = cuisine[randomRestaurant];
    loadedFunction();
}

function pickClickParadigm() {
    var randomRestaurant = Math.floor(Math.random() * (restaurantParadigm.length));
    document.getElementById('restaurantHTML').innerHTML = restaurantParadigm[randomRestaurant];
    // document.getElementById('cuisineHTML').innerHTML = cuisine[randomRestaurant];
    loadedFunction();
}

function pickClickJayaOne() {
    var randomRestaurant = Math.floor(Math.random() * (restaurantJayaOne.length));
    document.getElementById('restaurantHTML').innerHTML = restaurantJayaOne[randomRestaurant];
    // document.getElementById('cuisineHTML').innerHTML = cuisine[randomRestaurant];
    loadedFunction();
}

function pickClickOneUtama() {
    var randomRestaurant = Math.floor(Math.random() * (restaurantOneUtama.length));
    document.getElementById('restaurantHTML').innerHTML = restaurantOneUtama[randomRestaurant];
    // document.getElementById('cuisineHTML').innerHTML = cuisine[randomRestaurant];
    loadedFunction();
}

function pickClickStarling() {
    var randomRestaurant = Math.floor(Math.random() * (restaurantStarling.length));
    document.getElementById('restaurantHTML').innerHTML = restaurantStarling[randomRestaurant];
    // document.getElementById('cuisineHTML').innerHTML = cuisine[randomRestaurant];
    loadedFunction();
}

function pickClickAtria() {
    var randomRestaurant = Math.floor(Math.random() * (restaurantAtria.length));
    document.getElementById('restaurantHTML').innerHTML = restaurantAtria[randomRestaurant];
    // document.getElementById('cuisineHTML').innerHTML = cuisine[randomRestaurant];
    loadedFunction();
}