var restaurant = [
    //Unsorted
    'Provisions',
    'Big Wanton Mee',
    'Chicha Bonita',
    'Taco Bell',
    'Rocku Yakiniku',
    'Kuro',
    'Jakes Steak House',
    'Sala',

    // Paradigm + Vicinity
    'Kenny\'s Food Cart',
    'myBurgerLab',
    'Kar Heong Chicken Rice/Any Chicken Rice',
    'Undisclosed Location',
    'doudou',
    'Old Town White Coffee',
    'KD Hong Kong',
    'Pizza Hut',
    'Sushi Mentai',
    'Asian Rice Pot',
    'Acha\'s Curry House',
    'Nasi Lemak Bumbung',
    'Fatty Crab',
    'Sukiya',
    'Sushi Zanmai',
    'Chilli\'s',
    'Fei Fan Hotpot',
    'McDonalds',
    'KFC',
    'Ipoh Ais Kopi',
    'An Viet',
    'Penang Road Famous TeoChew Chendol',
    'Serai',
    'Canning Heritage Express',
    'Ginger Forever Thai',
    'Pork Meals',
    'Sepiring',
    'Sushi King',
    'Chicken Rice Shop',
    'Sukiya (Rice Bowl',
    'Aroi Thai',
    'FRK Noodle House',
    'GO Noodle',
    'Myeongdong Toppokki',
    'Canton Kitchen',
    'A&W',
    'Paradise Dynasty',
    'Sushi Zanmai',
    'Old Town',
    'I Love Yoo',
    'Nandos',
    'Burger King',
    'Fish n\' Co',
    'Seoul Garden',
    'd\'Italiene',
    'Kenny Rogers Roasters',
    'Ayamas',
    'Ah Cheng Laksa',
    'Kin Niku',
    'Food Arcade',
    'Salad Atelier',
    'Cravings',
    'Harum Manis',
    'Stuffd',
    'The Eatery',
    'Sushi Jiro',
    'Torii Tepanyaki',
    //If you're adding, make sure you're adding to the group below as well.

    // Jaya One + Vicinity
    'myBurgerLab',
    'Old Town White Coffee',
    'Ah Ma Kitchen',
    'Apple Samgyupsal',
    'Godubab Cafe',
    'Ippudo',
    'Kim Lian Kee',
    'Street Thai',
    'Subway',
    'Tedboy',
    'Tommy Thong Chai',
    'Uncle Chong Local Delights',
    'Sae Ma Eul',
    'Hannah Zen',
    'Lam Mee Ya',
    'Rumahku',
    'Shin Haru Tei',
    'Yakitori Syokudo Yae',
    'Ramenbar Shishido',
    'Picadilly',
    'Anjappar',
    'Bari Uma Ramen',
    'Enorme Italian Restaurant',
    'Grub by Ah Hong',
    'Zao',
    'Strangers at 47',
    'Jing Ze',
    'Aroi Mak Mak',
    'Kanna Curry House',
    'Tipsy Ball',
    'Omulab',
    'Big Leaf'
    // If you're adding, make sure you're adding to the group below as well.

    // Next Area
    //If you're adding, make sure you're adding to the group below as well.
]

var restaurantParadigm = [
    // Paradigm + Vicinity
    'Kenny\'s Food Cart',
    'myBurgerLab',
    'Kar Heong Chicken Rice/Any Chicken Rice',
    'Undisclosed Location',
    'doudou',
    'Old Town White Coffee',
    'KD Hong Kong',
    'Pizza Hut',
    'Sushi Mentai',
    'Asian Rice Pot',
    'Acha\'s Curry House',
    'Nasi Lemak Bumbung',
    'Fatty Crab',
    'Sukiya',
    'Sushi Zanmai',
    'Chilli\'s',
    'Fei Fan Hotpot',
    'McDonalds',
    'KFC',
    'Ipoh Ais Kopi',
    'An Viet',
    'Penang Road Famous TeoChew Chendol',
    'Serai',
    'Canning Heritage Express',
    'Ginger Forever Thai',
    'Pork Meals',
    'Sepiring',
    'Sushi King',
    'Chicken Rice Shop',
    'Sukiya (Rice Bowl',
    'Aroi Thai',
    'FRK Noodle House',
    'GO Noodle',
    'Myeongdong Toppokki',
    'Canton Kitchen',
    'A&W',
    'Paradise Dynasty',
    'Sushi Zanmai',
    'Old Town',
    'I Love Yoo',
    'Nandos',
    'Burger King',
    'Fish n\' Co',
    'Seoul Garden',
    'd\'Italiene',
    'Kenny Rogers Roasters',
    'Ayamas',
    'Ah Cheng Laksa',
    'Kin Niku',
    'Food Arcade',
    'Salad Atelier',
    'Cravings',
    'Harum Manis',
    'Stuffd',
    'The Eatery',
    'Sushi Jiro',
    'Torii Tepanyaki'
]

var restaurantJayaOne = [
    // Jaya One + Vicinity
    'myBurgerLab',
    'Old Town White Coffee',
    'Ah Ma Kitchen',
    'Apple Samgyupsal',
    'Godubab Cafe',
    'Ippudo',
    'Kim Lian Kee',
    'Street Thai',
    'Subway',
    'Tedboy',
    'Tommy Thong Chai',
    'Uncle Chong Local Delights',
    'Sae Ma Eul',
    'Hannah Zen',
    'Lam Mee Ya',
    'Rumahku',
    'Shin Haru Tei',
    'Yakitori Syokudo Yae',
    'Ramenbar Shishido',
    'Picadilly',
    'Anjappar',
    'Bari Uma Ramen',
    'Enorme Italian Restaurant',
    'Grub by Ah Hong',
    'Zao',
    'Strangers at 47',
    'Jing Ze',
    'Aroi Mak Mak',
    'Kanna Curry House',
    'Tipsy Ball',
    'Omulab',
    'Big Leaf'
]

function pickClick() {
    var randomRestaurant = Math.floor(Math.random() * (restaurant.length));
    document.getElementById('restaurantHTML').innerHTML = restaurant[randomRestaurant];
    // document.getElementById('cuisineHTML').innerHTML = cuisine[randomRestaurant];
}

function pickClickParadigm() {
    var randomRestaurant = Math.floor(Math.random() * (restaurantParadigm.length));
    document.getElementById('restaurantHTML').innerHTML = restaurantParadigm[randomRestaurant];
    // document.getElementById('cuisineHTML').innerHTML = cuisine[randomRestaurant];
}

function pickClickJayaOne() {
    var randomRestaurant = Math.floor(Math.random() * (restaurantJayaOne.length));
    document.getElementById('restaurantHTML').innerHTML = restaurantJayaOne[randomRestaurant];
    // document.getElementById('cuisineHTML').innerHTML = cuisine[randomRestaurant];
}